{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['batches.meta', 'data_batch_1', 'data_batch_2', 'data_batch_3', 'data_batch_4', 'data_batch_5', 'readme.html', 'test_batch']\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "import pickle\n",
    "import os\n",
    "\n",
    "CIFAR_DIR = './cifar-10-batches-py'\n",
    "print(os.listdir(CIFAR_DIR))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(50000, 3072)\n",
      "(50000,)\n",
      "(10000, 3072)\n",
      "(10000,)\n"
     ]
    }
   ],
   "source": [
    "def load_data(filename):\n",
    "    with open(filename, 'rb') as f:\n",
    "        data = pickle.load(f, encoding='bytes')\n",
    "        return data[b'data'], data[b'labels']\n",
    "\n",
    "class CifarData:\n",
    "    def __init__(self, filenames, need_shuffle):\n",
    "        all_data = []\n",
    "        all_labels = []\n",
    "        for filename in filenames:\n",
    "            data, labels = load_data(filename)\n",
    "            all_data.append(data)\n",
    "            all_labels.append(labels)\n",
    "        self._data = np.vstack(all_data)\n",
    "        self._data = self._data / 127.5 - 1  # 为了提高预测准确率，需要对数据进行归一化\n",
    "        self._labels = np.hstack(all_labels)\n",
    "        print(self._data.shape)\n",
    "        print(self._labels.shape)\n",
    "        \n",
    "        self._num_examples = self._data.shape[0]\n",
    "        self._need_shuffle = need_shuffle\n",
    "        self._indicator = 0  # 当前数据集指明遍历的位置\n",
    "        if self._need_shuffle:\n",
    "            self._shuffle_data()\n",
    "    \n",
    "    def _shuffle_data(self):\n",
    "        p = np.random.permutation(self._num_examples)  # 索引进行混排\n",
    "        self._data = self._data[p]\n",
    "        self._labels = self._labels[p]\n",
    "    \n",
    "    def next_batch(self, batch_size):\n",
    "        \"\"\"返回batch_size个样本\"\"\"\n",
    "        end_indicator = self._indicator + batch_size\n",
    "        if end_indicator > self._num_examples:\n",
    "            if self._need_shuffle:\n",
    "                self._shuffle_data()\n",
    "                self._indicator = 0\n",
    "                end_indicator = batch_size\n",
    "            else:\n",
    "                raise Exception(\"have no more examples\")\n",
    "        if end_indicator > self._num_examples:\n",
    "            raise Exception(\"batch size is larger than all examples\")\n",
    "        batch_data = self._data[self._indicator: end_indicator]\n",
    "        batch_labels = self._labels[self._indicator: end_indicator]\n",
    "        self._indicator = end_indicator\n",
    "        return batch_data, batch_labels\n",
    "\n",
    "train_filenames = [os.path.join(CIFAR_DIR, 'data_batch_%d' % i) for i in range(1, 6)]\n",
    "test_filenames = [os.path.join(CIFAR_DIR, 'test_batch')]\n",
    "\n",
    "train_data = CifarData(train_filenames, True)\n",
    "test_data = CifarData(test_filenames, False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From <ipython-input-3-eedc19c25915>:42: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use `tf.keras.layers.Conv2D` instead.\n",
      "WARNING:tensorflow:From D:\\Users\\Charles\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F881EA8C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F881EA8C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F881EA8C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F881EA8C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F881EA748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F881EA748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F881EA748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F881EA748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9A08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9A08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9A08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9A08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815642C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815642C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815642C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815642C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9A08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9A08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9A08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9A08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88214C48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88214C48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88214C48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88214C48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88214C48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88214C48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88214C48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88214C48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:From <ipython-input-3-eedc19c25915>:19: average_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use keras.layers.AveragePooling2D instead.\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x0000027F872DC948>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x0000027F872DC948>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x0000027F872DC948>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x0000027F872DC948>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88576208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88576208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88576208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88576208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88601B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88601B88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88601B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88601B88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9C08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9C08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9C08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9C08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9C08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9C08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9C08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F815B9C08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x0000027F815B9C08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x0000027F815B9C08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x0000027F815B9C08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.AveragePooling2D object at 0x0000027F815B9C08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F886568C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88627CC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88627CC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88627CC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000027F88627CC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:From <ipython-input-3-eedc19c25915>:55: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use keras.layers.dense instead.\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000027F8873B088>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000027F8873B088>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000027F8873B088>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x0000027F8873B088>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:From D:\\Users\\Charles\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\losses\\losses_impl.py:121: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.where in 2.0, which has the same broadcast rule as np.where\n"
     ]
    }
   ],
   "source": [
    "# 建立残差连接块\n",
    "def residual_block(x, output_channel):\n",
    "    \"\"\"残差连接块\"\"\"\n",
    "    input_channel = x.get_shape().as_list()[-1]\n",
    "    if input_channel * 2 == output_channel:\n",
    "        increase_dim = True\n",
    "        strides = (2, 2)\n",
    "    elif input_channel == output_channel:\n",
    "        increase_dim = False\n",
    "        strides = (1, 1)\n",
    "    else:\n",
    "        raise Exception(\"input channel can't match output channel\")\n",
    "    \n",
    "    conv1 = tf.layers.conv2d(x, output_channel, (3, 3), strides=strides, padding='same', activation=tf.nn.relu, name='conv1')\n",
    "    \n",
    "    conv2 = tf.layers.conv2d(conv1, output_channel, (3, 3), strides=(1, 1), padding='same', activation=tf.nn.relu, name='conv2')\n",
    "    \n",
    "    if increase_dim:\n",
    "        pooled_x = tf.layers.average_pooling2d(x, (2, 2), (2, 2), padding='valid')\n",
    "        \n",
    "        padded_x = tf.pad(pooled_x, [[0, 0], [0, 0], [0, 0], [input_channel // 2, input_channel // 2]])\n",
    "    else:\n",
    "        padded_x = x\n",
    "    \n",
    "    output_x = conv2 + padded_x\n",
    "    return output_x\n",
    "\n",
    "\n",
    "\n",
    "def res_net(x, num_residual_block, num_filter_base, class_num):\n",
    "    \"\"\"\n",
    "    x: 图片\n",
    "    num_residual_block: 残差连接块\n",
    "    num_filter_base: 通道数\n",
    "    class_num: \n",
    "    \"\"\"\n",
    "    num_subsampling = len(num_residual_block)\n",
    "    layers = []\n",
    "    # x: [None, width, height, channel] -> [width, height, channel]\n",
    "    input_size = x.get_shape().as_list()[1:]\n",
    "    with tf.variable_scope('conv0'):\n",
    "        conv0 = tf.layers.conv2d(x, num_filter_base, (3, 3), strides=(1, 1), padding='same', activation=tf.nn.relu, name='conv0')\n",
    "        layers.append(conv0)\n",
    "    for sample_id in range(num_subsampling):\n",
    "        for i in range(num_residual_block[sample_id]):\n",
    "            with tf.variable_scope('conv%d_%d' % (sample_id, i)):\n",
    "                conv = residual_block(layers[-1], num_filter_base*(2**sample_id))\n",
    "                layers.append(conv)\n",
    "    multiplier = 2 ** (num_subsampling - 1)\n",
    "    assert layers[-1].get_shape().as_list()[1:] == [input_size[0] / multiplier, input_size[1] / multiplier, num_filter_base * multiplier]\n",
    "    with tf.variable_scope('fc'):\n",
    "        # layer[-1].shape : [None, width, height, channel]\n",
    "        # kernal_size: image_width, image_height\n",
    "        global_pool = tf.reduce_mean(layers[-1], [1, 2])\n",
    "        logits = tf.layers.dense(global_pool, class_num)\n",
    "        layers.append(logits)\n",
    "    return layers[-1]\n",
    "\n",
    "\n",
    "\n",
    "# 计算图模型，先新建计算图，然后将数据塞入计算图中\n",
    "# placeholder 占位符的作用\n",
    "x = tf.placeholder(tf.float32, [None, 3072])  # None 样本数不确定，mini_batch\n",
    "# [None]\n",
    "y = tf.placeholder(tf.int64, [None])\n",
    "\n",
    "# 图片转换，reshape\n",
    "x_image = tf.reshape(x, [-1, 3, 32, 32])\n",
    "# 大小： 32*32\n",
    "x_image = tf.transpose(x_image, perm=[0, 2, 3, 1])\n",
    "\n",
    "\n",
    "\n",
    "y_ = res_net(x_image, [2, 3, 2], 32, 10)\n",
    "\n",
    "# 交叉熵损失数函数\n",
    "loss = tf.losses.sparse_softmax_cross_entropy(labels=y, logits=y_)\n",
    "# 执行原理\n",
    "# y_ -> softmax\n",
    "# y -> one_hot\n",
    "# loss -> ylogy_\n",
    "\n",
    "# 寻找最大概率值的 indices\n",
    "# 1 代表在第一个维度上\n",
    "predict = tf.argmax(y_, 1)\n",
    "# correct_prediction 结果可能是[0,1,0,0,1,1,1]\n",
    "correct_prediction = tf.equal(predict, y)\n",
    "# 求准确率，就是求平均值\n",
    "accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float64))\n",
    "\n",
    "# 在我们有了目标函数和损失函数，再定义梯度下降方法\n",
    "# 梯度下降的变种\n",
    "# 优化最小loss的值\n",
    "with tf.name_scope('train_op'):\n",
    "    train_op = tf.train.AdamOptimizer(1e-3).minimize(loss)\n",
    "# 计算图构建完成"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[Train] Step: 100, loss: 2.21734, acc: 0.25000\n",
      "[Train] Step: 200, loss: 1.97899, acc: 0.25000\n",
      "[Train] Step: 300, loss: 1.66922, acc: 0.30000\n",
      "[Train] Step: 400, loss: 1.41754, acc: 0.45000\n",
      "[Train] Step: 500, loss: 1.96771, acc: 0.25000\n",
      "[Train] Step: 600, loss: 1.92271, acc: 0.25000\n",
      "[Train] Step: 700, loss: 1.67884, acc: 0.35000\n",
      "[Train] Step: 800, loss: 1.33834, acc: 0.70000\n",
      "[Train] Step: 900, loss: 1.61402, acc: 0.45000\n",
      "[Train] Step: 1000, loss: 1.70022, acc: 0.35000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 1000, acc: 0.44750\n",
      "[Train] Step: 1100, loss: 1.14684, acc: 0.45000\n",
      "[Train] Step: 1200, loss: 1.20467, acc: 0.60000\n",
      "[Train] Step: 1300, loss: 1.40650, acc: 0.50000\n",
      "[Train] Step: 1400, loss: 1.81084, acc: 0.25000\n",
      "[Train] Step: 1500, loss: 1.33829, acc: 0.40000\n",
      "[Train] Step: 1600, loss: 1.15404, acc: 0.65000\n",
      "[Train] Step: 1700, loss: 1.30136, acc: 0.50000\n",
      "[Train] Step: 1800, loss: 1.35750, acc: 0.55000\n",
      "[Train] Step: 1900, loss: 1.32134, acc: 0.65000\n",
      "[Train] Step: 2000, loss: 1.43940, acc: 0.60000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 2000, acc: 0.52400\n",
      "[Train] Step: 2100, loss: 0.77096, acc: 0.75000\n",
      "[Train] Step: 2200, loss: 1.24385, acc: 0.45000\n",
      "[Train] Step: 2300, loss: 1.56244, acc: 0.50000\n",
      "[Train] Step: 2400, loss: 1.46424, acc: 0.40000\n",
      "[Train] Step: 2500, loss: 1.17700, acc: 0.55000\n",
      "[Train] Step: 2600, loss: 1.24188, acc: 0.55000\n",
      "[Train] Step: 2700, loss: 1.42445, acc: 0.40000\n",
      "[Train] Step: 2800, loss: 1.03719, acc: 0.60000\n",
      "[Train] Step: 2900, loss: 1.22808, acc: 0.55000\n",
      "[Train] Step: 3000, loss: 0.72975, acc: 0.70000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 3000, acc: 0.63500\n",
      "[Train] Step: 3100, loss: 0.99992, acc: 0.70000\n",
      "[Train] Step: 3200, loss: 1.11170, acc: 0.55000\n",
      "[Train] Step: 3300, loss: 0.88755, acc: 0.65000\n",
      "[Train] Step: 3400, loss: 1.29977, acc: 0.45000\n",
      "[Train] Step: 3500, loss: 1.24395, acc: 0.55000\n",
      "[Train] Step: 3600, loss: 0.87933, acc: 0.75000\n",
      "[Train] Step: 3700, loss: 1.15910, acc: 0.65000\n",
      "[Train] Step: 3800, loss: 0.62865, acc: 0.80000\n",
      "[Train] Step: 3900, loss: 1.32836, acc: 0.45000\n",
      "[Train] Step: 4000, loss: 1.00914, acc: 0.60000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 4000, acc: 0.63300\n",
      "[Train] Step: 4100, loss: 1.06735, acc: 0.65000\n",
      "[Train] Step: 4200, loss: 0.74862, acc: 0.70000\n",
      "[Train] Step: 4300, loss: 0.63353, acc: 0.80000\n",
      "[Train] Step: 4400, loss: 0.93312, acc: 0.65000\n",
      "[Train] Step: 4500, loss: 0.85825, acc: 0.65000\n",
      "[Train] Step: 4600, loss: 1.00173, acc: 0.70000\n",
      "[Train] Step: 4700, loss: 0.84327, acc: 0.65000\n",
      "[Train] Step: 4800, loss: 0.99132, acc: 0.55000\n",
      "[Train] Step: 4900, loss: 1.10363, acc: 0.70000\n",
      "[Train] Step: 5000, loss: 0.78656, acc: 0.65000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 5000, acc: 0.68800\n",
      "[Train] Step: 5100, loss: 0.59414, acc: 0.75000\n",
      "[Train] Step: 5200, loss: 0.70530, acc: 0.75000\n",
      "[Train] Step: 5300, loss: 0.56882, acc: 0.75000\n",
      "[Train] Step: 5400, loss: 0.58763, acc: 0.80000\n",
      "[Train] Step: 5500, loss: 1.07957, acc: 0.55000\n",
      "[Train] Step: 5600, loss: 0.67590, acc: 0.75000\n",
      "[Train] Step: 5700, loss: 0.98153, acc: 0.60000\n",
      "[Train] Step: 5800, loss: 0.52716, acc: 0.80000\n",
      "[Train] Step: 5900, loss: 0.71777, acc: 0.65000\n",
      "[Train] Step: 6000, loss: 0.99751, acc: 0.55000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 6000, acc: 0.67750\n",
      "[Train] Step: 6100, loss: 1.15617, acc: 0.50000\n",
      "[Train] Step: 6200, loss: 0.58660, acc: 0.85000\n",
      "[Train] Step: 6300, loss: 1.00174, acc: 0.65000\n",
      "[Train] Step: 6400, loss: 0.96852, acc: 0.65000\n",
      "[Train] Step: 6500, loss: 0.80697, acc: 0.70000\n",
      "[Train] Step: 6600, loss: 0.81259, acc: 0.70000\n",
      "[Train] Step: 6700, loss: 0.95425, acc: 0.65000\n",
      "[Train] Step: 6800, loss: 0.93619, acc: 0.60000\n",
      "[Train] Step: 6900, loss: 0.50560, acc: 0.90000\n",
      "[Train] Step: 7000, loss: 0.37265, acc: 0.85000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 7000, acc: 0.73500\n",
      "[Train] Step: 7100, loss: 0.79900, acc: 0.75000\n",
      "[Train] Step: 7200, loss: 1.05450, acc: 0.65000\n",
      "[Train] Step: 7300, loss: 0.62112, acc: 0.80000\n",
      "[Train] Step: 7400, loss: 0.72104, acc: 0.70000\n",
      "[Train] Step: 7500, loss: 0.83962, acc: 0.65000\n",
      "[Train] Step: 7600, loss: 0.53286, acc: 0.85000\n",
      "[Train] Step: 7700, loss: 0.67796, acc: 0.80000\n",
      "[Train] Step: 7800, loss: 0.31306, acc: 0.90000\n",
      "[Train] Step: 7900, loss: 0.77457, acc: 0.70000\n",
      "[Train] Step: 8000, loss: 1.07404, acc: 0.55000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 8000, acc: 0.74700\n",
      "[Train] Step: 8100, loss: 0.39041, acc: 0.85000\n",
      "[Train] Step: 8200, loss: 0.73522, acc: 0.75000\n",
      "[Train] Step: 8300, loss: 0.86274, acc: 0.70000\n",
      "[Train] Step: 8400, loss: 1.04784, acc: 0.65000\n",
      "[Train] Step: 8500, loss: 0.93018, acc: 0.65000\n",
      "[Train] Step: 8600, loss: 0.69356, acc: 0.75000\n",
      "[Train] Step: 8700, loss: 0.83453, acc: 0.65000\n",
      "[Train] Step: 8800, loss: 0.70833, acc: 0.75000\n",
      "[Train] Step: 8900, loss: 0.89049, acc: 0.70000\n",
      "[Train] Step: 9000, loss: 0.37723, acc: 0.95000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 9000, acc: 0.74250\n",
      "[Train] Step: 9100, loss: 0.39717, acc: 0.80000\n",
      "[Train] Step: 9200, loss: 0.39745, acc: 0.85000\n",
      "[Train] Step: 9300, loss: 0.51543, acc: 0.80000\n",
      "[Train] Step: 9400, loss: 0.98695, acc: 0.60000\n",
      "[Train] Step: 9500, loss: 0.43174, acc: 0.80000\n",
      "[Train] Step: 9600, loss: 0.35677, acc: 0.95000\n",
      "[Train] Step: 9700, loss: 0.42989, acc: 0.85000\n",
      "[Train] Step: 9800, loss: 0.46278, acc: 0.85000\n",
      "[Train] Step: 9900, loss: 0.46629, acc: 0.80000\n",
      "[Train] Step: 10000, loss: 0.79941, acc: 0.70000\n",
      "(10000, 3072)\n",
      "(10000,)\n",
      "[Test ] Step: 10000, acc: 0.75150\n"
     ]
    }
   ],
   "source": [
    "init = tf.global_variables_initializer()\n",
    "batch_size = 20\n",
    "train_steps = 10000\n",
    "test_steps = 100\n",
    "\n",
    "# train 10k: 73.4%\n",
    "with tf.Session() as sess:\n",
    "    sess.run(init)\n",
    "    for i in range(train_steps):\n",
    "        batch_data, batch_labels = train_data.next_batch(batch_size)\n",
    "        loss_val, acc_val, _ = sess.run(\n",
    "            [loss, accuracy, train_op],\n",
    "            feed_dict={\n",
    "                x: batch_data,\n",
    "                y: batch_labels})\n",
    "        if (i+1) % 100 == 0:\n",
    "            print('[Train] Step: %d, loss: %4.5f, acc: %4.5f' \n",
    "                  % (i+1, loss_val, acc_val))\n",
    "        if (i+1) % 1000 == 0:\n",
    "            test_data = CifarData(test_filenames, False)\n",
    "            all_test_acc_val = []\n",
    "            for j in range(test_steps):\n",
    "                test_batch_data, test_batch_labels \\\n",
    "                    = test_data.next_batch(batch_size)\n",
    "                test_acc_val = sess.run(\n",
    "                    [accuracy],\n",
    "                    feed_dict = {\n",
    "                        x: test_batch_data, \n",
    "                        y: test_batch_labels\n",
    "                    })\n",
    "                all_test_acc_val.append(test_acc_val)\n",
    "            test_acc = np.mean(all_test_acc_val)\n",
    "            print('[Test ] Step: %d, acc: %4.5f' % (i+1, test_acc))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
